version: "2"
services:
  data:
    container_name: test_data
    build: ./data
    volumes:
      - ./data/src:/var/www
      - /var/lib/mysql
  db:
    container_name: test_db
    image: mariadb
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: pass
  fpm:
    container_name: test_fpm
    build: ./fpm
    volumes_from:
      - data
    privileged: true    
  nginx:
    container_name: test_nginx
    build: ./nginx
    volumes_from:
      - data
    ports:
      - "80:80"
    privileged: true
  composer:
    container_name: test_composer    
    build: ./composer
    volumes_from:
      - data
