FROM busybox

MAINTAINER ap0sec <apo.t.laboratory@gmail.com>

RUN mkdir -p /var/lib && \
    mkdir -p /var/lib/mysql && \
    mkdir -p /var/www/html && \
    mkdir -p /var/www/sock

WORKDIR /var/www/sock
